### ISSUE TITLE
no child pages for optech workshop

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/bitcointranscripts#216]
[optech workshop](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/bitcoinops/schnorr-taproot-workshop-2019/_index.md)

**Comment by kouloumos** [comment]
It seems that this is currently [part of Misc](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/misc/2019-09-27-schnorr-taproot-workshop.md). We can either move it there and break existing links or delete this category from Bitcoinops, which still leaves it empty. We could delete the whole Bitcoinops folder it if we were not expecting any other transcripts, but because the Bitcoin Optech Newsletter is now discussed in weekly twitter spaces, and the recordings will be part of a podcast feed, I believe that there is grounds there for those transcripts to be here.

Therefore, I think moving it from misc and creating an alias in order to not break the existing link is a good way forward, see https://github.com/bitcointranscripts/bitcointranscripts/pull/219.
